/**
 * MOS Translator Seed Script
 * Run: node server/seed-mos.mjs
 * Seeds mos_codes and civilian_career_paths tables with research data
 */
import { createConnection } from "mysql2/promise";
import * as dotenv from "dotenv";
dotenv.config();

const db = await createConnection(process.env.DATABASE_URL);

// ─── Helper ───────────────────────────────────────────────────────────────────
async function upsertMos(code, branch, title, description, category, keySkills, searchKeywords) {
  const [existing] = await db.execute("SELECT id FROM mos_codes WHERE code = ?", [code]);
  if (existing.length > 0) {
    await db.execute(
      `UPDATE mos_codes SET branch=?, title=?, description=?, category=?, keySkills=?, searchKeywords=?, updatedAt=NOW() WHERE code=?`,
      [branch, title, description, category, JSON.stringify(keySkills), searchKeywords, code]
    );
    return existing[0].id;
  }
  const [result] = await db.execute(
    `INSERT INTO mos_codes (code, branch, title, description, category, keySkills, searchKeywords, isActive, createdAt, updatedAt)
     VALUES (?, ?, ?, ?, ?, ?, ?, 1, NOW(), NOW())`,
    [code, branch, title, description, category, JSON.stringify(keySkills), searchKeywords]
  );
  return result.insertId;
}

async function upsertCareerPath(mosId, jobTitle, industry, description, salaryMin, salaryMax, salaryMedian, transitionDifficulty, timeToHireMonths, requiredCerts, recommendedCerts, transferableSkills, skillsGap, exampleEmployers, isTopPath, displayOrder) {
  const [existing] = await db.execute(
    "SELECT id FROM civilian_career_paths WHERE mosId = ? AND jobTitle = ?",
    [mosId, jobTitle]
  );
  if (existing.length > 0) {
    await db.execute(
      `UPDATE civilian_career_paths SET industry=?, description=?, salaryMin=?, salaryMax=?, salaryMedian=?, transitionDifficulty=?, timeToHireMonths=?, requiredCerts=?, recommendedCerts=?, transferableSkills=?, skillsGap=?, exampleEmployers=?, isTopPath=?, displayOrder=?, updatedAt=NOW() WHERE id=?`,
      [industry, description, salaryMin, salaryMax, salaryMedian, transitionDifficulty, timeToHireMonths, JSON.stringify(requiredCerts), JSON.stringify(recommendedCerts), JSON.stringify(transferableSkills), JSON.stringify(skillsGap), JSON.stringify(exampleEmployers), isTopPath ? 1 : 0, displayOrder, existing[0].id]
    );
    return;
  }
  await db.execute(
    `INSERT INTO civilian_career_paths (mosId, jobTitle, industry, description, salaryMin, salaryMax, salaryMedian, transitionDifficulty, timeToHireMonths, requiredCerts, recommendedCerts, transferableSkills, skillsGap, exampleEmployers, isTopPath, displayOrder, createdAt, updatedAt)
     VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, NOW(), NOW())`,
    [mosId, jobTitle, industry, description, salaryMin, salaryMax, salaryMedian, transitionDifficulty, timeToHireMonths, JSON.stringify(requiredCerts), JSON.stringify(recommendedCerts), JSON.stringify(transferableSkills), JSON.stringify(skillsGap), JSON.stringify(exampleEmployers), isTopPath ? 1 : 0, displayOrder]
  );
}

// ─── Seed Data ────────────────────────────────────────────────────────────────
console.log("Seeding MOS codes...");

// 11B - Infantryman
let mosId = await upsertMos("11B", "army", "Infantryman", "Ground combat specialist trained in small unit tactics, weapons operation, patrol techniques, and close-quarters battle.", "Combat", ["Leadership under pressure", "Weapons proficiency", "Physical fitness", "Attention to detail", "Team coordination", "Emergency response", "Tactical planning"], "infantry combat soldier patrol weapons leadership security law enforcement");
await upsertCareerPath(mosId, "Police Officer / Sheriff Deputy", "Law Enforcement", "Leverage military discipline and weapons training to serve in municipal, county, or state law enforcement. Veteran preference gives you a hiring edge.", 45000, 110000, 65000, "easy", 8, ["POST Certification (Police Academy 4-6 months)", "Valid driver's license"], ["Associate's degree", "First Aid/CPR"], ["Weapons handling", "High-stress decision making", "Report writing", "Shift work tolerance", "Physical fitness"], ["Civilian law enforcement procedures", "Community policing", "State-specific laws"], ["City Police Departments", "County Sheriff's Office", "State Police", "CBP", "ICE", "DEA"], true, 1);
await upsertCareerPath(mosId, "Executive Protection Specialist", "Private Security", "Provide personal security for high-net-worth individuals, executives, or celebrities. High earning potential with overseas opportunities.", 55000, 150000, 85000, "moderate", 6, ["State security guard license", "Armed security certification"], ["EP training (ESI, EPI)", "Concealed carry permit", "First Aid/CPR"], ["Weapons proficiency", "Situational awareness", "Patrol procedures", "Emergency response"], ["Executive protection protocols", "Advance work", "Threat assessment"], ["Pinkerton", "Allied Universal", "G4S", "Blackwater/Constellis"], false, 2);
await upsertCareerPath(mosId, "Federal Corrections Officer (BOP)", "Government", "Work in federal prisons managing inmate populations. Faster hiring than police departments with strong federal benefits.", 38000, 85000, 55000, "easy", 3, ["State corrections academy (6-12 weeks)", "High school diploma"], ["Associate's degree preferred"], ["Following strict procedures", "Accountability tracking", "High-stress management", "De-escalation", "Shift work"], ["Inmate management", "Corrections-specific laws", "Verbal de-escalation techniques"], ["Federal Bureau of Prisons", "State DOC", "Private corrections (CoreCivic, GEO Group)"], false, 3);
await upsertCareerPath(mosId, "Skilled Tradesperson (Electrician/HVAC)", "Skilled Trades", "Leverage your physical fitness, attention to detail, and ability to follow procedures in a high-demand trade. GI Bill covers many apprenticeships.", 40000, 110000, 65000, "moderate", 24, ["Trade apprenticeship (2-5 years)", "State trade license"], ["OSHA 10/30", "CDL (for some roles)"], ["Attention to detail", "Following procedures", "Physical fitness", "Safety-first mindset", "Tool accountability"], ["Trade-specific technical skills", "Electrical codes", "HVAC systems"], ["IBEW (electricians union)", "UA (plumbers union)", "SMACNA (HVAC)"], false, 4);
await upsertCareerPath(mosId, "Private Military Contractor", "Defense Contracting", "Apply your combat experience directly in overseas security roles. Highest pay but demanding lifestyle with frequent travel to high-threat areas.", 70000, 200000, 110000, "easy", 3, ["Security clearance (preferred)", "High Threat Contractor training"], ["PSD course", "Advanced weapons certs", "EMT background helpful"], ["Combat experience", "Weapons proficiency", "Tactical planning", "Team leadership"], ["Contractor-specific legal frameworks", "OCONUS procedures"], ["Constellis", "Triple Canopy", "DRS Technologies", "MPRI"], false, 5);

// 11C - Mortarman
mosId = await upsertMos("11C", "army", "Indirect Fire Infantryman (Mortarman)", "Operates and maintains mortar weapons systems, performs fire direction control, and provides indirect fire support.", "Combat", ["Precision calculations", "Fire direction control", "Team coordination", "Equipment maintenance", "Mathematical accuracy"], "mortar artillery fire support indirect fire calculations");
await upsertCareerPath(mosId, "Police Officer", "Law Enforcement", "Strong leadership and weapons background transfers directly to law enforcement careers.", 45000, 110000, 65000, "easy", 8, ["POST Certification"], ["Associate's degree"], ["Weapons handling", "Team coordination", "Physical fitness"], ["Civilian law enforcement procedures"], ["City/County Police Departments", "State Police"], true, 1);
await upsertCareerPath(mosId, "Fire Protection Specialist", "Emergency Services", "Precision under pressure and team coordination translate well to firefighting and emergency response.", 45000, 80000, 60000, "moderate", 6, ["NFPA 1001 (Fire Fighter I/II)", "EMT-B"], ["Hazmat Operations", "Fire Inspector cert"], ["Emergency response", "Team coordination", "Physical fitness", "Equipment maintenance"], ["Fire science coursework", "Civilian emergency protocols"], ["Municipal Fire Departments", "Airport ARFF", "Industrial Fire Brigades"], false, 2);

// 12B - Combat Engineer
mosId = await upsertMos("12B", "army", "Combat Engineer", "Constructs and demolishes structures, breaches obstacles, performs route clearance, and supports mobility/counter-mobility operations.", "Engineering", ["Construction management", "Demolition safety", "Blueprint reading", "Heavy equipment operation", "Project coordination", "Safety protocols"], "combat engineer construction demolition project management civil engineering");
await upsertCareerPath(mosId, "Construction Project Manager", "Construction", "Your experience managing complex construction and demolition projects under pressure is directly applicable to civilian construction management.", 65000, 120000, 85000, "moderate", 12, ["OSHA 30", "PMP (Project Management Professional)"], ["PE license (with engineering degree)", "AutoCAD certification"], ["Construction management", "Blueprint reading", "Safety protocols", "Team leadership", "Project coordination"], ["Civilian building codes", "Contract management", "Budget management"], ["Turner Construction", "Bechtel", "Fluor", "Army Corps of Engineers"], true, 1);
await upsertCareerPath(mosId, "Explosive Ordnance Disposal (EOD) Technician", "Government/Defense", "Specialized demolition knowledge translates directly to civilian EOD roles with federal agencies.", 55000, 95000, 72000, "easy", 4, ["Federal EOD training (provided)", "Security clearance"], ["Hazmat Technician cert"], ["Demolition expertise", "Safety protocols", "Precision work", "High-stress operations"], ["Civilian EOD procedures", "Federal regulations"], ["FBI", "ATF", "State Police EOD", "Military contractors"], false, 2);
await upsertCareerPath(mosId, "Electrician / Plumber", "Skilled Trades", "Construction and systems knowledge provides a strong foundation for licensed trade work.", 45000, 100000, 65000, "moderate", 24, ["Trade apprenticeship", "State license"], ["OSHA 30", "CDL"], ["Construction knowledge", "Safety protocols", "Physical fitness", "Equipment operation"], ["Trade-specific technical skills", "Electrical/plumbing codes"], ["IBEW", "UA", "Local trade unions"], false, 3);

// 15W - UAS Operator
mosId = await upsertMos("15W", "army", "Unmanned Aircraft Systems Operator", "Operates and maintains unmanned aerial systems (drones) for reconnaissance, surveillance, and target acquisition.", "Aviation/Technology", ["Drone operation", "Aerial reconnaissance", "Systems maintenance", "Data analysis", "Situational awareness", "Mission planning"], "drone UAS UAV unmanned aircraft pilot FAA commercial remote sensing GIS");
await upsertCareerPath(mosId, "Commercial Drone Pilot / UAS Specialist", "Technology", "Your military UAS experience is directly transferable to the booming commercial drone industry. FAA Part 107 is a quick cert to obtain.", 55000, 100000, 72000, "easy", 2, ["FAA Part 107 Remote Pilot Certificate"], ["Manufacturer certifications (DJI, Autel)", "GIS certification"], ["Drone operation", "Mission planning", "Airspace awareness", "Data collection"], ["FAA commercial regulations", "Client communication", "Business development"], ["DJI Enterprise", "Skydio", "Percepto", "Inspection companies", "Film/media companies"], true, 1);
await upsertCareerPath(mosId, "Remote Sensing / GIS Analyst", "Technology/Government", "Combine your aerial data collection experience with geospatial analysis for government agencies, environmental firms, and tech companies.", 65000, 100000, 80000, "moderate", 6, ["FAA Part 107", "GIS certification (GISP)"], ["ArcGIS certification", "Python for GIS"], ["Aerial reconnaissance", "Data analysis", "Mission planning", "Systems operation"], ["GIS software (ArcGIS, QGIS)", "Data visualization", "Geospatial analysis"], ["USGS", "NOAA", "Esri", "Environmental consulting firms"], false, 2);

// 17C - Cyber Operations
mosId = await upsertMos("17C", "army", "Cyber Operations Specialist", "Conducts offensive and defensive cyber operations, network exploitation, and vulnerability analysis.", "Technology", ["Network security", "Threat analysis", "Vulnerability assessment", "Incident response", "Penetration testing", "Malware analysis"], "cyber cybersecurity network security hacking penetration testing SOC analyst");
await upsertCareerPath(mosId, "Cybersecurity Analyst", "Technology", "Your offensive cyber training is among the most sought-after skills in the civilian market. Six-figure salaries are achievable quickly.", 80000, 150000, 110000, "easy", 3, ["CompTIA Security+", "CEH (Certified Ethical Hacker)"], ["CISSP", "OSCP", "GPEN"], ["Network security", "Threat analysis", "Vulnerability assessment", "Incident response"], ["Compliance frameworks (NIST, SOC2)", "Cloud security", "Business communication"], ["Booz Allen Hamilton", "SAIC", "Leidos", "CrowdStrike", "Palo Alto Networks"], true, 1);
await upsertCareerPath(mosId, "Penetration Tester / Red Team Operator", "Technology", "Offensive cyber skills translate directly to ethical hacking and red team engagements for Fortune 500 companies.", 90000, 160000, 120000, "easy", 4, ["OSCP (Offensive Security Certified Professional)", "CEH"], ["GPEN", "GXPN", "CRTO"], ["Offensive cyber operations", "Vulnerability exploitation", "Network penetration", "Reporting"], ["Engagement scoping", "Client communication", "Legal frameworks"], ["Rapid7", "Synack", "NCC Group", "Crowdstrike Services"], false, 2);
await upsertCareerPath(mosId, "SOC Analyst / Threat Intelligence", "Technology", "Defensive cyber experience supports Security Operations Center roles monitoring and responding to threats in real time.", 70000, 120000, 90000, "easy", 2, ["CompTIA Security+", "CompTIA CySA+"], ["SIEM certifications (Splunk, QRadar)", "GCIA"], ["Threat analysis", "Incident response", "Network monitoring", "Malware analysis"], ["SIEM tools", "Ticketing systems", "Compliance reporting"], ["Mandiant", "IBM Security", "Deloitte", "Banks and financial institutions"], false, 3);

// 18D - Special Forces Medic
mosId = await upsertMos("18D", "army", "Special Forces Medical Sergeant", "Provides advanced trauma care, performs field surgery, trains indigenous forces in medical techniques, and manages medical operations.", "Healthcare", ["Advanced trauma care", "Surgical assistance", "Pharmacology", "Patient assessment", "Medical training", "Emergency medicine"], "special forces medic physician assistant paramedic nurse healthcare trauma surgery");
await upsertCareerPath(mosId, "Physician Assistant", "Healthcare", "Your 18D training is the closest military equivalent to a PA. With bridge programs, you can earn your PA-C faster than a civilian starting from scratch.", 110000, 160000, 130000, "challenging", 36, ["PA-C License", "NCCPA Board Exam", "Bachelor's degree minimum"], ["ACNP-BC", "Emergency Medicine specialty"], ["Advanced trauma care", "Surgical assistance", "Pharmacology", "Patient assessment", "Procedures"], ["PA school curriculum", "Civilian clinical rotations", "Electronic health records"], ["VA Healthcare", "Hospitals", "Urgent care chains", "Military contractors"], true, 1);
await upsertCareerPath(mosId, "Flight Paramedic / Critical Care Paramedic", "Healthcare/EMS", "Your trauma skills translate directly to high-acuity EMS roles. Flight paramedic is the civilian equivalent of your combat medicine role.", 55000, 90000, 70000, "easy", 6, ["NREMT-P (National Registry Paramedic)", "State EMS license"], ["CCEMTP (Critical Care)", "FP-C (Flight Paramedic)"], ["Advanced trauma care", "Patient assessment", "Pharmacology", "Emergency procedures"], ["Civilian EMS protocols", "Electronic patient care reports", "Hospital handoffs"], ["Air Methods", "PHI Air Medical", "HEMS companies", "Level 1 Trauma Centers"], false, 2);

// 25B - IT Specialist
mosId = await upsertMos("25B", "army", "Information Technology Specialist", "Installs, operates, and maintains Army IT systems, networks, and hardware. Provides technical support and network administration.", "Technology", ["Network administration", "Troubleshooting", "Hardware maintenance", "Security protocols", "Systems administration", "Help desk support"], "IT information technology network administrator systems admin cybersecurity cloud help desk");
await upsertCareerPath(mosId, "Systems Administrator", "Technology", "Your hands-on IT experience managing Army networks translates directly to enterprise sysadmin roles.", 60000, 100000, 78000, "easy", 3, ["CompTIA A+", "CompTIA Network+"], ["Microsoft MCSA/MCSE", "Linux+", "VMware VCP"], ["Network administration", "Hardware maintenance", "Troubleshooting", "Security protocols"], ["Enterprise ticketing systems", "Cloud platforms", "Virtualization"], ["Government contractors", "Healthcare IT", "Financial services", "Tech companies"], true, 1);
await upsertCareerPath(mosId, "Network Engineer", "Technology", "Advance from sysadmin to network engineering with Cisco certifications. Strong demand and excellent salary growth.", 75000, 130000, 100000, "moderate", 6, ["CCNA (Cisco Certified Network Associate)", "CompTIA Network+"], ["CCNP", "JNCIA", "AWS Networking Specialty"], ["Network administration", "Routing and switching", "Troubleshooting", "Security"], ["Advanced routing protocols", "SD-WAN", "Network automation"], ["Cisco", "Juniper", "AT&T", "Verizon", "Government contractors"], false, 2);
await upsertCareerPath(mosId, "Cybersecurity Analyst", "Technology", "Add a Security+ cert to your IT background and pivot into the high-demand, high-pay cybersecurity field.", 80000, 140000, 105000, "moderate", 6, ["CompTIA Security+", "CEH"], ["CISSP", "CySA+", "CISM"], ["Security protocols", "Network administration", "Troubleshooting", "Systems knowledge"], ["Threat analysis", "Incident response", "Compliance frameworks"], ["Booz Allen", "SAIC", "Leidos", "Banks", "Healthcare"], false, 3);
await upsertCareerPath(mosId, "Cloud Engineer / DevOps", "Technology", "Cloud is the fastest-growing segment of IT. Your systems background plus cloud certs can land you six figures quickly.", 90000, 160000, 120000, "moderate", 9, ["AWS Solutions Architect Associate", "Azure Administrator (AZ-104)"], ["AWS DevOps Professional", "Kubernetes (CKA)", "Terraform"], ["Systems administration", "Network knowledge", "Scripting basics"], ["Cloud architecture", "Infrastructure as Code", "CI/CD pipelines"], ["Amazon", "Microsoft", "Google", "Accenture", "Deloitte"], false, 4);

// 25U - Signal Support Systems Specialist (Allen's MOS)
mosId = await upsertMos("25U", "army", "Signal Support Systems Specialist", "Installs, operates, and maintains communications equipment including radio systems, satellite communications, and network infrastructure. Provides technical support for signal operations.", "Technology", ["Radio communications", "Satellite systems", "Network installation", "Troubleshooting", "Technical documentation", "Field communications", "Systems integration"], "signal communications radio satellite network technician telecommunications field service engineer");
await upsertCareerPath(mosId, "Telecommunications Technician", "Technology", "Your signal training maps directly to telecom technician roles installing and maintaining communications infrastructure.", 55000, 90000, 70000, "easy", 3, ["CompTIA Network+", "FCC General Radiotelephone Operator License (GROL)"], ["BICSI RCDD", "CompTIA A+"], ["Radio communications", "Satellite systems", "Network installation", "Troubleshooting", "Technical documentation"], ["Fiber optics", "Civilian telecom standards", "Customer service"], ["AT&T", "Verizon", "T-Mobile", "Dish Network", "Government contractors"], true, 1);
await upsertCareerPath(mosId, "Network Technician / Field Service Engineer", "Technology", "Field service engineering leverages your hands-on systems installation and troubleshooting experience in a high-demand role.", 55000, 110000, 78000, "easy", 4, ["CCNA (Cisco)", "CompTIA Network+"], ["CompTIA A+", "Vendor-specific certs"], ["Network installation", "Troubleshooting", "Systems integration", "Technical documentation"], ["Enterprise networking equipment", "Customer-facing communication", "Service ticketing systems"], ["Cisco", "Juniper", "IBM", "HP Enterprise", "Defense contractors"], false, 2);
await upsertCareerPath(mosId, "IT Project Manager", "Technology", "Your experience coordinating signal operations and managing communications equipment supports a transition into IT project management.", 75000, 130000, 100000, "moderate", 12, ["PMP (Project Management Professional)", "CompTIA Project+"], ["ITIL Foundation", "Agile/Scrum certifications"], ["Project coordination", "Technical documentation", "Team leadership", "Systems integration"], ["Formal project management methodologies", "Budget management", "Stakeholder communication"], ["Booz Allen Hamilton", "SAIC", "Leidos", "Accenture Federal", "DXC Technology"], false, 3);
await upsertCareerPath(mosId, "RPA Developer / Automation Engineer", "Technology", "Combine your technical background with automation skills to build bots and workflows. High demand, excellent pay, and growing field.", 80000, 140000, 105000, "moderate", 12, ["Automation Anywhere Certified Advanced RPA Professional", "UiPath RPA Developer"], ["CompTIA Security+", "Python programming", "SQL fundamentals"], ["Systems integration", "Technical troubleshooting", "Process documentation", "Attention to detail"], ["RPA platforms (Automation Anywhere, UiPath, Power Automate)", "Programming fundamentals", "Business process analysis"], ["Automation Anywhere", "UiPath", "Deloitte", "Accenture", "Banks and insurance companies"], false, 4);

// 35F - Intelligence Analyst
mosId = await upsertMos("35F", "army", "Intelligence Analyst", "Collects, analyzes, and produces all-source intelligence products. Performs pattern analysis, target development, and intelligence reporting.", "Intelligence", ["Data analysis", "Report writing", "Pattern recognition", "All-source intelligence", "Geospatial analysis", "Threat assessment"], "intelligence analyst data analyst business intelligence government contractor security clearance GEOINT HUMINT");
await upsertCareerPath(mosId, "Intelligence Analyst (Government/Contractor)", "Government/Defense", "Your clearance and analytical skills are in high demand with federal agencies and defense contractors. Often the highest-paying direct transition.", 70000, 130000, 95000, "easy", 3, ["Active TS/SCI clearance (if held)", "GEOINT certification"], ["HUMINT certification", "SIGINT certification", "OSINT certification"], ["Intelligence analysis", "Report writing", "Pattern recognition", "All-source analysis", "Threat assessment"], ["Contractor-specific tools", "Business development (for consulting roles)"], ["Booz Allen Hamilton", "SAIC", "Leidos", "CIA", "DIA", "NSA"], true, 1);
await upsertCareerPath(mosId, "Data Analyst / Business Intelligence Analyst", "Technology/Business", "Your analytical skills and pattern recognition translate directly to business intelligence roles in the private sector.", 70000, 120000, 90000, "moderate", 9, ["SQL fundamentals", "Tableau Desktop Specialist"], ["Power BI certification", "Python for data analysis", "Google Data Analytics cert"], ["Data analysis", "Pattern recognition", "Report writing", "Attention to detail"], ["Business context", "SQL/Python", "Data visualization tools", "Stakeholder communication"], ["Deloitte", "McKinsey", "Amazon", "Microsoft", "Financial services firms"], false, 2);
await upsertCareerPath(mosId, "Risk Analyst / Fraud Analyst", "Finance/Insurance", "Threat assessment and pattern recognition skills apply directly to financial risk and fraud analysis roles.", 65000, 110000, 85000, "moderate", 6, ["CRISC (Certified in Risk and Information Systems Control)"], ["CISM", "CFE (Certified Fraud Examiner)", "CISA"], ["Threat assessment", "Pattern recognition", "Report writing", "Analytical thinking"], ["Financial regulations", "Risk frameworks", "Banking systems"], ["JPMorgan Chase", "Bank of America", "Insurance companies", "Consulting firms"], false, 3);

// 42A - HR Specialist
mosId = await upsertMos("42A", "army", "Human Resources Specialist", "Manages personnel records, processes benefits and pay, handles assignments, and supports HR operations for Army units.", "Administration", ["Personnel management", "Records management", "Benefits administration", "Compliance", "Data entry", "Customer service", "Payroll processing"], "human resources HR generalist recruiter payroll benefits administrator personnel management");
await upsertCareerPath(mosId, "HR Generalist / HR Manager", "Business", "Army HR experience maps directly to civilian HR roles. Your knowledge of benefits, records, and personnel management is immediately applicable.", 55000, 95000, 72000, "easy", 4, ["PHR (Professional in Human Resources)", "SHRM-CP"], ["SHRM-SCP", "MBA (for senior roles)"], ["Personnel management", "Records management", "Benefits administration", "Compliance", "Customer service"], ["Civilian HR software (Workday, ADP)", "Employment law", "Performance management"], ["Amazon", "Walmart", "Healthcare systems", "Government agencies", "Consulting firms"], true, 1);
await upsertCareerPath(mosId, "Recruiter / Talent Acquisition Specialist", "Business", "Your experience with military accessions and personnel management translates well to corporate recruiting.", 50000, 90000, 65000, "easy", 3, ["SHRM-CP preferred"], ["LinkedIn Recruiter certification", "PHR"], ["Personnel management", "Interviewing", "Records management", "Communication"], ["Applicant tracking systems (ATS)", "Sourcing strategies", "Employment law"], ["Amazon", "Deloitte", "Military-friendly employers", "Staffing agencies"], false, 2);

// 68W - Combat Medic
mosId = await upsertMos("68W", "army", "Combat Medic Specialist", "Provides emergency medical treatment, trauma care, and preventive medicine. Manages medical equipment and supplies, and supports medical operations.", "Healthcare", ["Emergency medicine", "Patient assessment", "Trauma care", "Pharmacology", "Triage", "Medical documentation", "Preventive medicine"], "combat medic EMT paramedic nurse physician assistant healthcare emergency medicine trauma");
await upsertCareerPath(mosId, "EMT / Paramedic", "Healthcare/EMS", "Your combat medic training exceeds EMT-Basic requirements. With NREMT testing, you can certify quickly and start working immediately.", 35000, 70000, 50000, "easy", 2, ["NREMT-B (EMT-Basic) or NREMT-P (Paramedic)", "State EMS license"], ["ACLS", "PALS", "PHTLS"], ["Emergency medicine", "Patient assessment", "Trauma care", "Pharmacology", "Triage"], ["Civilian EMS protocols", "Electronic patient care reports", "Hospital communication"], ["AMR", "Rural Metro", "Fire departments", "Hospital EMS systems"], true, 1);
await upsertCareerPath(mosId, "Registered Nurse (with schooling)", "Healthcare", "With an RN bridge program (typically 2-3 years), your medical background gives you a significant advantage over civilian nursing students.", 70000, 120000, 90000, "challenging", 30, ["RN License (NCLEX-RN)", "Associate's or Bachelor's in Nursing"], ["CCRN", "CEN", "TNCC"], ["Patient assessment", "Emergency medicine", "Pharmacology", "Medical documentation", "Team coordination"], ["Nursing school curriculum", "Electronic health records (Epic, Cerner)", "Hospital protocols"], ["VA Healthcare", "Hospital systems", "Travel nursing agencies"], false, 2);
await upsertCareerPath(mosId, "Medical Sales Representative", "Healthcare/Sales", "Your clinical knowledge and professional communication skills are highly valued in medical device and pharmaceutical sales.", 65000, 120000, 85000, "moderate", 6, ["No specific cert required — clinical knowledge is the credential"], ["Medical sales training programs"], ["Medical knowledge", "Professional communication", "Reliability", "Attention to detail"], ["Sales techniques", "Territory management", "CRM software", "Healthcare procurement"], ["Stryker", "Medtronic", "Johnson & Johnson", "Abbott", "Zimmer Biomet"], false, 3);
await upsertCareerPath(mosId, "Healthcare Administrator", "Healthcare", "Combine your medical background with business skills to manage clinics, hospitals, or VA facilities.", 65000, 110000, 82000, "moderate", 18, ["MHA (Master of Health Administration) or relevant bachelor's"], ["FACHE (Fellow of ACHE)", "PMP"], ["Medical operations", "Team coordination", "Documentation", "Compliance"], ["Healthcare finance", "Regulatory compliance", "Strategic planning", "EHR systems"], ["VA Healthcare", "Hospital systems", "Urgent care chains", "Insurance companies"], false, 4);

// 88M - Motor Transport Operator
mosId = await upsertMos("88M", "army", "Motor Transport Operator", "Operates wheeled vehicles to transport personnel and supplies, conducts convoy operations, and performs vehicle maintenance.", "Logistics/Transportation", ["Vehicle operation", "Route planning", "Logistics coordination", "Safety compliance", "Convoy operations", "Vehicle maintenance"], "truck driver CDL logistics transportation supply chain fleet manager convoy");
await upsertCareerPath(mosId, "Commercial Truck Driver (CDL-A)", "Transportation", "Your military driving experience and discipline are highly valued by trucking companies. CDL-A is a quick cert with immediate job placement.", 55000, 90000, 70000, "easy", 2, ["CDL-A (Commercial Driver's License)", "DOT Medical Certificate"], ["HAZMAT endorsement", "Doubles/Triples endorsement", "Tanker endorsement"], ["Vehicle operation", "Route planning", "Safety compliance", "Logistics coordination"], ["Civilian DOT regulations", "ELD (Electronic Logging Device)", "Customer interaction"], ["Werner", "JB Hunt", "Schneider", "Amazon Freight", "UPS Freight"], true, 1);
await upsertCareerPath(mosId, "Logistics Coordinator / Supply Chain Analyst", "Logistics", "Your convoy operations experience translates to logistics coordination roles managing shipments and supply chains.", 50000, 80000, 62000, "moderate", 6, ["APICS CSCP or CPIM (preferred)", "CDL-A helpful"], ["Six Sigma Green Belt", "PMP"], ["Logistics coordination", "Route planning", "Vehicle operations", "Safety compliance"], ["ERP systems (SAP, Oracle)", "Supply chain software", "Data analysis"], ["Amazon", "UPS", "FedEx", "Military contractors", "Manufacturing companies"], false, 2);

// 92A - Automated Logistical Specialist
mosId = await upsertMos("92A", "army", "Automated Logistical Specialist", "Manages inventory, supply chain operations, and warehouse functions. Operates automated supply systems and maintains property accountability.", "Logistics", ["Inventory management", "Supply chain management", "ERP systems", "Data entry", "Property accountability", "Warehouse operations"], "supply chain logistics inventory management warehouse operations ERP SAP analyst");
await upsertCareerPath(mosId, "Supply Chain Manager / Analyst", "Logistics/Business", "Your Army supply chain experience is directly applicable to civilian logistics roles. APICS certifications significantly boost your salary.", 65000, 110000, 85000, "easy", 6, ["APICS CSCP (Certified Supply Chain Professional)"], ["APICS CPIM", "Six Sigma Green Belt", "PMP"], ["Inventory management", "Supply chain operations", "ERP systems", "Data analysis", "Property accountability"], ["Civilian ERP systems (SAP, Oracle)", "Demand forecasting", "Vendor management"], ["Amazon", "Walmart", "Boeing", "Lockheed Martin", "Defense contractors"], true, 1);
await upsertCareerPath(mosId, "Warehouse Manager / Operations Manager", "Logistics", "Lead warehouse teams using the same accountability and process discipline you developed in the Army.", 55000, 85000, 68000, "easy", 3, ["OSHA 30", "Forklift certification"], ["Six Sigma Green Belt", "APICS CPIM"], ["Inventory management", "Team leadership", "Process compliance", "Safety protocols"], ["Warehouse management systems (WMS)", "KPI tracking", "Civilian HR practices"], ["Amazon", "UPS", "FedEx", "Costco", "Manufacturing companies"], false, 2);

// Navy - IT
mosId = await upsertMos("IT", "navy", "Information Systems Technician", "Maintains and operates Navy computer networks, communications systems, and information technology infrastructure aboard ships and shore facilities.", "Technology", ["Network management", "Communications systems", "Cybersecurity", "Systems administration", "Technical troubleshooting", "Satellite communications"], "navy IT network administrator cybersecurity systems administrator communications");
await upsertCareerPath(mosId, "Network Administrator", "Technology", "Your Navy IT experience managing shipboard networks translates directly to enterprise network administration.", 65000, 105000, 82000, "easy", 3, ["CompTIA Network+", "CCNA"], ["CompTIA Security+", "Microsoft MCSA"], ["Network management", "Communications systems", "Troubleshooting", "Documentation"], ["Enterprise networking", "Cloud platforms", "Ticketing systems"], ["Government contractors", "Tech companies", "Financial services", "Healthcare IT"], true, 1);
await upsertCareerPath(mosId, "Cybersecurity Analyst", "Technology", "Add Security+ to your IT background and pivot into the high-demand cybersecurity field.", 80000, 140000, 105000, "moderate", 6, ["CompTIA Security+", "CEH"], ["CISSP", "CySA+"], ["Cybersecurity", "Network management", "Systems administration"], ["Threat analysis", "Compliance frameworks", "Incident response"], ["Booz Allen", "SAIC", "Leidos", "NSA", "DHS"], false, 2);

// Navy - HM (Hospital Corpsman)
mosId = await upsertMos("HM", "navy", "Hospital Corpsman", "Provides medical care, emergency medicine, and preventive medicine support. Works alongside Navy physicians and surgeons in clinical and field settings.", "Healthcare", ["Emergency medicine", "Patient care", "Surgical assistance", "Pharmacology", "Medical documentation", "Preventive medicine"], "hospital corpsman EMT paramedic nurse surgical tech healthcare medical");
await upsertCareerPath(mosId, "EMT / Paramedic", "Healthcare/EMS", "Your corpsman training exceeds EMT requirements. Quick certification path with immediate employment.", 35000, 70000, 50000, "easy", 2, ["NREMT-B or NREMT-P", "State EMS license"], ["ACLS", "PALS"], ["Emergency medicine", "Patient care", "Pharmacology", "Triage"], ["Civilian EMS protocols", "Electronic patient care reports"], ["AMR", "Fire departments", "Hospital EMS"], true, 1);
await upsertCareerPath(mosId, "Surgical Technologist", "Healthcare", "Your OR experience as a corpsman maps directly to surgical tech roles in civilian hospitals.", 50000, 75000, 62000, "easy", 6, ["CST (Certified Surgical Technologist)", "Associate's degree helpful"], ["CSFA (Certified Surgical First Assistant)"], ["Surgical assistance", "Sterile technique", "Instrument handling", "Patient care"], ["Civilian OR protocols", "Electronic health records"], ["Hospital systems", "Ambulatory surgery centers", "VA Healthcare"], false, 2);

// Air Force - 3D1X2 Cyber
mosId = await upsertMos("3D1X2", "air_force", "Cyber Systems Operations", "Operates and maintains Air Force cyberspace systems, provides network defense, and supports cyber operations.", "Technology", ["Network defense", "Systems operations", "Cybersecurity", "Cloud computing", "Incident response", "Security monitoring"], "air force cyber cybersecurity network defense cloud security DevSecOps");
await upsertCareerPath(mosId, "Cybersecurity Engineer", "Technology", "Air Force cyber training is among the most rigorous in the military. Civilian employers actively recruit USAF cyber veterans.", 90000, 160000, 120000, "easy", 3, ["CompTIA Security+", "CISSP"], ["CEH", "OSCP", "CCSP"], ["Network defense", "Systems operations", "Cybersecurity", "Incident response"], ["Compliance frameworks", "Cloud security", "Business communication"], ["Booz Allen", "SAIC", "Leidos", "CrowdStrike", "Palo Alto Networks"], true, 1);
await upsertCareerPath(mosId, "Cloud Security Engineer", "Technology", "Combine your cyber background with cloud certifications for one of the highest-paying tech roles.", 95000, 165000, 130000, "moderate", 6, ["AWS Security Specialty", "CCSP"], ["Azure Security Engineer", "GCP Professional Cloud Security"], ["Network defense", "Systems security", "Incident response"], ["Cloud architecture", "DevSecOps", "Container security"], ["Amazon", "Microsoft", "Google", "Accenture", "Deloitte"], false, 2);

// Air Force - 2A3X3 Aircraft Maintenance
mosId = await upsertMos("2A3X3", "air_force", "Tactical Aircraft Maintenance", "Maintains tactical fighter and attack aircraft, performs inspections, troubleshoots malfunctions, and ensures aircraft airworthiness.", "Aviation", ["Aircraft maintenance", "Quality control", "Technical documentation", "Troubleshooting", "Safety protocols", "Avionics systems"], "aircraft mechanic A&P aviation maintenance FAA airframe powerplant inspector");
await upsertCareerPath(mosId, "Aircraft Mechanic / A&P Technician", "Aviation", "Your military aircraft maintenance experience is directly transferable. FAA A&P certification is the key credential.", 65000, 110000, 85000, "easy", 6, ["FAA Airframe & Powerplant (A&P) License"], ["IA Authorization", "Avionics certification"], ["Aircraft maintenance", "Quality control", "Troubleshooting", "Technical documentation", "Safety"], ["Civilian aviation regulations (FAR/AIM)", "Commercial aircraft differences", "MRO systems"], ["Delta TechOps", "American Airlines", "Boeing", "Lockheed Martin", "Northrop Grumman"], true, 1);
await upsertCareerPath(mosId, "Aviation Quality Inspector", "Aviation", "Your quality control experience translates to aviation inspection roles ensuring airworthiness compliance.", 65000, 100000, 80000, "moderate", 9, ["FAA A&P License", "ASQ CQI (Certified Quality Inspector)"], ["IA Authorization", "Six Sigma Green Belt"], ["Quality control", "Technical documentation", "Inspection procedures", "Safety protocols"], ["FAA regulations", "Quality management systems", "Audit procedures"], ["Boeing", "Airbus", "MRO companies", "FAA (as inspector)"], false, 2);

// Marine Corps - 0311 Rifleman
mosId = await upsertMos("0311", "marine_corps", "Rifleman", "Ground combat specialist trained in small unit tactics, patrol operations, and close-quarters battle. The foundation of Marine Corps infantry.", "Combat", ["Tactical operations", "Weapons proficiency", "Leadership", "Physical fitness", "Team coordination", "Patrol operations"], "marine infantry rifleman combat patrol law enforcement security police");
await upsertCareerPath(mosId, "Police Officer / Law Enforcement", "Law Enforcement", "Marine Corps discipline and weapons training are highly valued in law enforcement. Many departments actively recruit Marines.", 45000, 110000, 65000, "easy", 8, ["POST Certification (Police Academy)"], ["Associate's degree", "First Aid/CPR"], ["Weapons handling", "Physical fitness", "Leadership", "Team coordination", "Discipline"], ["Civilian law enforcement procedures", "Community policing", "State laws"], ["City/County Police", "State Police", "FBI", "DEA", "CBP"], true, 1);
await upsertCareerPath(mosId, "Security Specialist / Contractor", "Private Security", "Marine Corps combat experience is among the most respected in the private security industry.", 40000, 150000, 75000, "easy", 3, ["State security license", "Armed security certification"], ["EP training", "Concealed carry permit"], ["Weapons proficiency", "Tactical operations", "Physical fitness", "Leadership"], ["Civilian security protocols", "Client communication"], ["Constellis", "Allied Universal", "G4S", "Government contractors"], false, 2);

// Marine Corps - 0651 Cyber Network Operator
mosId = await upsertMos("0651", "marine_corps", "Cyber Network Operator", "Operates and defends Marine Corps networks, performs cybersecurity operations, and supports information operations.", "Technology", ["Network defense", "Cybersecurity", "Systems operations", "Incident response", "Network monitoring"], "marine corps cyber network security cybersecurity analyst engineer");
await upsertCareerPath(mosId, "Network Security Engineer", "Technology", "Marine Corps cyber training prepares you well for enterprise network security roles.", 85000, 150000, 115000, "easy", 3, ["CCNP Security", "CompTIA Security+"], ["CISSP", "CEH", "OSCP"], ["Network defense", "Cybersecurity", "Systems operations", "Incident response"], ["Enterprise network architecture", "Compliance frameworks", "Cloud security"], ["Cisco", "Palo Alto Networks", "Fortinet", "Government contractors"], true, 1);

// Coast Guard - BM
mosId = await upsertMos("BM", "coast_guard", "Boatswain's Mate", "Conducts deck operations, navigation, search and rescue, and maritime law enforcement. Operates and maintains small boats and deck equipment.", "Maritime/Law Enforcement", ["Navigation", "Seamanship", "Search and rescue", "Law enforcement", "Boat operations", "Maritime safety"], "coast guard maritime navigation merchant marine port security law enforcement SAR");
await upsertCareerPath(mosId, "Maritime Officer / Merchant Marine", "Maritime", "Your seamanship and navigation experience translates directly to commercial maritime careers. USCG credentials are highly valued.", 65000, 130000, 90000, "easy", 6, ["USCG Merchant Mariner Credential (MMC)", "STCW Basic Safety Training"], ["OUPV (6-Pack) or 100-ton Master license", "Advanced firefighting cert"], ["Navigation", "Seamanship", "Boat operations", "Safety protocols", "Team leadership"], ["Commercial maritime regulations", "Cargo operations", "Port procedures"], ["Crowley Maritime", "Maersk", "Carnival Cruise", "NOAA", "Army Corps of Engineers"], true, 1);
await upsertCareerPath(mosId, "Port Security Specialist", "Government/Security", "Maritime law enforcement experience is directly applicable to port security and customs roles.", 55000, 90000, 70000, "easy", 4, ["TWIC (Transportation Worker ID Credential)", "Port security certification"], ["CBP Officer training"], ["Maritime law enforcement", "Security procedures", "Navigation", "Team operations"], ["Port security regulations", "Customs procedures", "Cargo inspection"], ["CBP", "TSA", "Port Authorities", "Maritime security companies"], false, 2);

console.log("✅ MOS seed complete!");
await db.end();
